# Deploying Basketball Stats App to shinyapps.io

## Setup

In the console in RStudio:

``` r
install.packages("rsconnect")
library(rsconnect)
install.packages("shiny")
install.packages("DT")
```

## Setup ShinyApps.io account

1.  Create/login to shinyapps.io account - choose the free version!
2.  Navigate: Account → Tokens → Show → Show Secret
3.  Copy the whole thing to clipboard.
4.  Paste into RStudio console.

## Generate your app.R file

1.  Go to your sport's championships.csv file on GitHub and copy the raw version.
2.  Go to Claude.ai or ChatGPT and paste the contents into the prompt, then add the following prompt:

```         
Using the tidyverse and read_csv, create a basic Shiny app using R allowing users to browse and search the attached CSV file. Presume that the project directory structure exists, with no static assets and the CSV file is at the root.
```


3.  Download the file or copy the results into a file called app.R and put it inside the folder of your sport.
4.  Click the "Run App" button to test it out. If it doesn't work try to debug why and a solution.

## Deploy Your App

Adjust the folder path below to match your sport and then copy and paste that line into the RStudio console.

``` r
rsconnect::deployApp('fall/soccer', appMode = "shiny")
```

It should give you a URL to go to if the deployment is successful.
